version: '3'
services:
  db:
    image: mariadb:10.3
    container_name: mysql_drupal
    environment:
      MYSQL_ROOT_PASSWORD: drupal
    ports:
      - "33111:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d/:ro
    restart: always
  db-test:
    image: mariadb:10.3
    container_name: mysql_drupal_test
    environment:
      MYSQL_ROOT_PASSWORD: drupal
    ports:
      - "33112:3306"
    volumes:
      - db_data_test:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d/:ro
    restart: always
  drupal:
    container_name: drupal
    depends_on:
      - db
    build: .
    ports:
      - "2345:80"
      - "2443:443"
    volumes:
      - ./:/opt/drupal
      - /opt/drupal/vendor
    restart: always
    environment:
      - SITE_INSTALL=1
      - XDEBUG_INSTALL=1
      - CMS_ENVIRONMENT=development
  drupal-test:
    container_name: drupal_test
    depends_on:
      - db-test
    build: .
    ports:
      - "3456:80"
      - "3443:443"
    volumes:
      - ./:/opt/drupal
      - /opt/drupal/vendor
      - ./features/files:/home/seluser/files
    restart: always
    environment:
      - SITE_INSTALL=1
      - XDEBUG_INSTALL=1
      - CMS_ENVIRONMENT=test
  selenium.dev:
    image: selenium/standalone-chrome-debug:3.12.0
    container_name: selenium
    volumes:
      - ./features/files:/home/seluser/files
volumes:
  db_data:
  db_data_test:
