version: '3'
services:
  db:
    image: mariadb:10.3
    container_name: mysql_drupal
    environment:
      MYSQL_ROOT_PASSWORD: drupal
    ports:
      - "33111:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d/:ro
    restart: always
  drupal:
    container_name: drupal
    depends_on:
      - db
    build: .
    ports:
      - "2345:80"
      - "2443:443"
    volumes:
      - ./:/opt/drupal
      - /opt/drupal/vendor
    restart: always
    environment:
      - SITE_INSTALL=1
      - XDEBUG_INSTALL=1
  selenium.dev:
    image: selenium/standalone-chrome-debug:3.12.0
    container_name: selenium
volumes:
  db_data:
