<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_node_view().
 * @param array $build
 * @param EntityInterface $entity
 * @param EntityViewDisplayInterface $display
 * @param $view_mode
 */
function basic_content_node_view(
  array &$build,
  \Drupal\Core\Entity\EntityInterface $entity,
  EntityViewDisplayInterface $display,
  $view_mode
) {
  $bundle = $entity->bundle();
  if ($bundle == 'product') {
    // Access field data.
    $protected = $entity->get('field_protected')->get(0)->value;
    if ($protected) {
      $build['body'][0]['#cookie_content_blocker'] = true;
    }
  }

}
