blocked_message: 'You have not yet given permission to place the required cookies. Accept the required cookies to view this content.'
show_button: true
button_text: 'Show content'
enable_click_consent_change: true
consent_awareness:
  accepted:
    event:
      name: cookiebotConsentAcceptRestricted
      selector: window
    cookie:
      operator: '==='
      name: cookiebot-consent--restricted
      value: '1'
  declined:
    event:
      name: cookiebotConsentDeclineRestricted
      selector: window
    cookie:
      operator: '==='
      name: cookiebot-consent--restricted
      value: '0'
  change:
    event:
      name: cookiebotConsentRenew
      selector: window
_core:
  default_config_hash: rgXeqZIe6gop-4LsbTtqhiiLSvEQNTxpYg9wO02O-6Y
